### ISSUE TITLE
Problem: No code samples

### ISSUE THREAD

**Issue by sappo** [Snorenotify/Snorenotify#10]
Hi,
it would be really nice if you could provide some code samples to get started with Snorenotify. Because right now I don't really have a clue what to do.

Thanks in advance!

**Comment by TheOneRing** [comment]
Hi for 0.5 I would recommend to have a look on https://github.com/Snorenotify/snore-send/blob/0.5/src/main.cpp#L49 .

For master https://github.com/Snorenotify/snore-send/blob/master/src/main.cpp#L46 .

I would recommend to use a 0.5 version.

Cheers

**Comment by sappo** [comment]
That's very helpful, thanks.
I'd tried to compile snorenotify under window but wasn't able to resolve
the ecm dependency. Any advice?
Am 26.02.2015 12:02 schrieb "TheOneRing" <notifications@github.com>:

**Comment by TheOneRing** [comment]
ECM can be found here https://projects.kde.org/projects/kdesupport/extra-cmake-modules

**Comment by TheOneRing** [comment]
and thanks for pointing out I added the description in https://github.com/Snorenotify/Snorenotify/commit/10cfd68dc0bcaeaefbeb1be5243e0569e78b8ef3
