### ISSUE TITLE
Unable to compile on ubuntu 14.04

### ISSUE THREAD

**Issue by sappo** [Snorenotify/Snorenotify#11]
I'm trying to get Snorenotify compiling on Ubuntu 14.04 and I'm unable to get ECM going

So far I tried:

```
cmake .. -DCMAKE_PREFIX_PATH=<path-to-ecm>/extra-cmake-modules
cmake .. -DCMAKE_PREFIX_PATH=<path-to-ecm>/extra-cmake-modules/find-modules
cmake .. -DCMAKE_PREFIX_PATH=<path-to-ecm>/extra-cmake-modules/kde-modules
cmake .. -DCMAKE_PREFIX_PATH=<path-to-ecm>/extra-cmake-modules/modules
```
But always the following error has been shown.
```
CMake Error at CMakeLists.txt:6 (find_package):
  Could not find a package configuration file provided by "ECM" (requested
  version 1.7.0) with any of the following names:

    ECMConfig.cmake
    ecm-config.cmake

  Add the installation prefix of "ECM" to CMAKE_PREFIX_PATH or set "ECM_DIR"
  to a directory containing one of the above files.  If "ECM" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
```

**Comment by TheOneRing** [comment]
As mentioned before master is experimental. New in master are settings, and currently I'm not sure how the settings will work in the final version and code will change a lot.
Therefor it uses features of ecm 1.7 which isn't available on kubuntu yet. Also it looks like "extra-cmake-modules" isn't installed at all on your system.

You can install the newest version of ecm manually from https://projects.kde.org/projects/kdesupport/extra-cmake-modules
