### ISSUE TITLE
Disable the ability to change settings by using the mouse wheel

### ISSUE THREAD

**Issue by towlie** [Snorenotify/Snorenotify#18]
You accidantally change settings because of that by just scrolling through the client settings.

**Comment by TheOneRing** [comment]
Hi this is the default behaviour of a QSpinBox, but it might be a focus issue.
Could you please provide a screenshot of the widget the SettingsWidget is embedded in.

**Comment by towlie** [comment]
You can change everything accidantally by scrolling except the checkbox. (so even the tab "Allgemein" and Primary Backends) This also happens with snorenotify.exe
![widget](https://cloud.githubusercontent.com/assets/6986141/9060444/3808f81e-3ab4-11e5-927b-06f85088aae4.jpg)
